import type { Enrollment } from "@/lib/types";

export const mockEnrollments: Enrollment[] = [
  {
    id: "enroll-001",
    studentId: "user-008",
    courseId: "course-001",
    intakeId: "intake-001",
    enrollmentDate: "2024-01-16",
    status: "active",
    paymentStatus: "completed",
  },
  {
    id: "enroll-002",
    studentId: "user-009",
    courseId: "course-001",
    intakeId: "intake-001",
    enrollmentDate: "2024-01-17",
    status: "active",
    paymentStatus: "completed",
  },
  {
    id: "enroll-003",
    studentId: "user-010",
    courseId: "course-002",
    intakeId: "intake-003",
    enrollmentDate: "2024-01-22",
    status: "active",
    paymentStatus: "completed",
  },
  {
    id: "enroll-004",
    studentId: "user-011",
    courseId: "course-003",
    intakeId: "intake-004",
    enrollmentDate: "2024-03-05",
    status: "payment_pending",
    paymentStatus: "pending",
  },
  {
    id: "enroll-005",
    studentId: "user-012",
    courseId: "course-004",
    intakeId: "intake-005",
    enrollmentDate: "2024-09-02",
    status: "active",
    paymentStatus: "completed",
  },
  {
    id: "enroll-006",
    studentId: "user-008",
    courseUnitId: "unit-012",
    enrollmentDate: "2024-10-05",
    status: "payment_pending",
    paymentStatus: "pending",
  },
  {
    id: "enroll-007",
    studentId: "user-009",
    courseId: "course-005",
    intakeId: "intake-006",
    enrollmentDate: "2023-06-05",
    status: "completed",
    paymentStatus: "completed",
  },
  {
    id: "enroll-008",
    studentId: "user-010",
    courseId: "course-006",
    enrollmentDate: "2024-02-10",
    status: "dropped",
    paymentStatus: "failed",
  },
  {
    id: "enroll-009",
    studentId: "user-011",
    courseId: "course-007",
    intakeId: "intake-007",
    enrollmentDate: "2024-10-03",
    status: "active",
    paymentStatus: "completed",
  },
  {
    id: "enroll-010",
    studentId: "user-012",
    courseId: "course-001",
    intakeId: "intake-002",
    enrollmentDate: "2024-08-05",
    status: "active",
    paymentStatus: "completed",
  },
];
