import type { Examination, ExamSubmission } from "@/lib/types";

export const mockExaminations: Examination[] = [
  {
    id: "exam-001",
    title: "Data Structures Mid-Semester Quiz",
    courseUnitId: "unit-001",
    type: "quiz",
    instructions: "Answer all 20 multiple-choice questions. Each question carries 5 marks.",
    passMark: 50,
    timeLimit: 45,
    maxAttempts: 2,
    startDate: "2024-11-20",
    endDate: "2024-11-22",
    status: "active",
  },
  {
    id: "exam-002",
    title: "Software Engineering Assignment 1",
    courseUnitId: "unit-002",
    type: "assignment",
    instructions: "Design a class diagram for an e-commerce system. Submit as PDF.",
    passMark: 50,
    maxAttempts: 1,
    startDate: "2024-11-15",
    endDate: "2024-11-30",
    status: "active",
  },
  {
    id: "exam-003",
    title: "Database Systems Final Exam",
    courseUnitId: "unit-003",
    type: "final_exam",
    instructions: "Answer 5 out of 7 questions. Show all working for SQL queries.",
    passMark: 50,
    timeLimit: 180,
    maxAttempts: 1,
    startDate: "2024-12-10",
    endDate: "2024-12-10",
    status: "active",
  },
  {
    id: "exam-004",
    title: "Marketing Principles Quiz",
    courseUnitId: "unit-004",
    type: "quiz",
    instructions: "Complete 15 questions on marketing mix and consumer behavior.",
    passMark: 50,
    timeLimit: 30,
    maxAttempts: 3,
    startDate: "2024-11-18",
    endDate: "2024-11-20",
    status: "active",
  },
  {
    id: "exam-005",
    title: "Financial Accounting Final Exam",
    courseUnitId: "unit-005",
    type: "final_exam",
    instructions: "Prepare a complete set of financial statements from the given trial balance.",
    passMark: 55,
    timeLimit: 150,
    maxAttempts: 1,
    startDate: "2024-12-15",
    endDate: "2024-12-15",
    status: "active",
  },
  {
    id: "exam-006",
    title: "Structural Analysis Assignment",
    courseUnitId: "unit-006",
    type: "assignment",
    instructions: "Calculate reactions and draw shear force and bending moment diagrams for the given beam.",
    passMark: 50,
    maxAttempts: 1,
    startDate: "2024-11-25",
    endDate: "2024-12-05",
    status: "active",
  },
  {
    id: "exam-007",
    title: "Web Development Practical Test",
    courseUnitId: "unit-008",
    type: "quiz",
    instructions: "Build a responsive landing page using HTML and CSS within the time limit.",
    passMark: 50,
    timeLimit: 60,
    maxAttempts: 1,
    startDate: "2024-11-28",
    endDate: "2024-11-28",
    status: "active",
  },
  {
    id: "exam-008",
    title: "Constitutional Law Essay",
    courseUnitId: "unit-011",
    type: "assignment",
    instructions: "Write a 2000-word essay on the separation of powers in Uganda's governance system.",
    passMark: 50,
    maxAttempts: 1,
    startDate: "2024-11-01",
    endDate: "2024-11-15",
    status: "inactive",
  },
];

export const mockExamSubmissions: ExamSubmission[] = [
  {
    id: "sub-001",
    examId: "exam-001",
    studentId: "user-008",
    studentName: "Aisha Nakato",
    submissionDate: "2024-11-20T10:45:00Z",
    score: 85,
    status: "passed",
    attemptNumber: 1,
  },
  {
    id: "sub-002",
    examId: "exam-001",
    studentId: "user-009",
    studentName: "Brian Ochieng",
    submissionDate: "2024-11-20T11:30:00Z",
    score: 45,
    status: "failed",
    attemptNumber: 1,
  },
  {
    id: "sub-003",
    examId: "exam-001",
    studentId: "user-009",
    studentName: "Brian Ochieng",
    submissionDate: "2024-11-21T09:00:00Z",
    score: 62,
    status: "passed",
    attemptNumber: 2,
  },
  {
    id: "sub-004",
    examId: "exam-001",
    studentId: "user-012",
    studentName: "Esther Nambi",
    submissionDate: "2024-11-21T14:20:00Z",
    score: 72,
    status: "passed",
    attemptNumber: 1,
  },
  {
    id: "sub-005",
    examId: "exam-002",
    studentId: "user-008",
    studentName: "Aisha Nakato",
    submissionDate: "2024-11-25T16:00:00Z",
    score: 78,
    status: "passed",
    attemptNumber: 1,
  },
  {
    id: "sub-006",
    examId: "exam-004",
    studentId: "user-010",
    studentName: "Grace Atim",
    submissionDate: "2024-11-18T15:00:00Z",
    score: 90,
    status: "passed",
    attemptNumber: 1,
  },
  {
    id: "sub-007",
    examId: "exam-008",
    studentId: "user-011",
    studentName: "David Mugisha",
    submissionDate: "2024-11-10T23:59:00Z",
    score: 0,
    status: "pending",
    attemptNumber: 1,
  },
];
