import type { StudyMaterial } from "@/lib/types";

export const mockMaterials: StudyMaterial[] = [
  {
    id: "mat-001",
    title: "Introduction to Algorithms - Lecture Notes",
    description: "Comprehensive notes covering Big-O notation, recursion, and divide-and-conquer strategies.",
    courseUnitId: "unit-001",
    type: "pdf",
    fileUrl: "/files/algorithms-notes.pdf",
    fileSize: 2450000,
    uploadDate: "2024-02-10",
    downloadCount: 156,
    uploadedBy: "user-004",
  },
  {
    id: "mat-002",
    title: "Sorting Algorithms Video Tutorial",
    description: "Visual explanation of quicksort, mergesort, and heapsort with complexity analysis.",
    courseUnitId: "unit-001",
    type: "video",
    fileUrl: "/files/sorting-tutorial.mp4",
    fileSize: 85000000,
    uploadDate: "2024-02-15",
    downloadCount: 98,
    uploadedBy: "user-004",
  },
  {
    id: "mat-003",
    title: "Software Design Patterns Presentation",
    description: "Slides covering Singleton, Factory, Observer, and Strategy patterns with Java examples.",
    courseUnitId: "unit-002",
    type: "presentation",
    fileUrl: "/files/design-patterns.pptx",
    fileSize: 5200000,
    uploadDate: "2024-03-01",
    downloadCount: 72,
    uploadedBy: "user-005",
  },
  {
    id: "mat-004",
    title: "SQL Practice Assignment",
    description: "Hands-on exercises for writing complex queries, joins, and subqueries.",
    courseUnitId: "unit-003",
    type: "assignment",
    fileUrl: "/files/sql-assignment.pdf",
    fileSize: 450000,
    uploadDate: "2024-03-10",
    downloadCount: 134,
    uploadedBy: "user-004",
  },
  {
    id: "mat-005",
    title: "Marketing Case Studies - East Africa",
    description: "Collection of marketing case studies from Ugandan and Kenyan companies.",
    courseUnitId: "unit-004",
    type: "pdf",
    fileUrl: "/files/marketing-cases.pdf",
    fileSize: 3800000,
    uploadDate: "2024-02-20",
    downloadCount: 45,
    uploadedBy: "user-006",
  },
  {
    id: "mat-006",
    title: "Financial Statements Workshop",
    description: "Step-by-step guide to preparing income statements and balance sheets.",
    courseUnitId: "unit-005",
    type: "pdf",
    fileUrl: "/files/financial-statements.pdf",
    fileSize: 1800000,
    uploadDate: "2024-03-05",
    downloadCount: 67,
    uploadedBy: "user-007",
  },
  {
    id: "mat-007",
    title: "Structural Analysis Video Lecture",
    description: "Detailed walkthrough of beam deflection calculations and moment distribution.",
    courseUnitId: "unit-006",
    type: "video",
    fileUrl: "/files/structural-analysis.mp4",
    fileSize: 120000000,
    uploadDate: "2024-04-01",
    downloadCount: 38,
    uploadedBy: "user-005",
  },
  {
    id: "mat-008",
    title: "HTML & CSS Fundamentals",
    description: "Beginner-friendly guide to building responsive web pages.",
    courseUnitId: "unit-008",
    type: "pdf",
    fileUrl: "/files/html-css-guide.pdf",
    fileSize: 2100000,
    uploadDate: "2024-09-10",
    downloadCount: 89,
    uploadedBy: "user-004",
  },
  {
    id: "mat-009",
    title: "Curriculum Design Framework Presentation",
    description: "Overview of backward design and competency-based curriculum models.",
    courseUnitId: "unit-009",
    type: "presentation",
    fileUrl: "/files/curriculum-framework.pptx",
    fileSize: 4500000,
    uploadDate: "2023-07-15",
    downloadCount: 23,
    uploadedBy: "user-007",
  },
  {
    id: "mat-010",
    title: "Constitutional Law Reading Pack",
    description: "Selected readings from the 1995 Uganda Constitution and landmark court cases.",
    courseUnitId: "unit-011",
    type: "pdf",
    fileUrl: "/files/constitutional-law.pdf",
    fileSize: 6700000,
    uploadDate: "2024-02-28",
    downloadCount: 54,
    uploadedBy: "user-007",
  },
];
