import type { Notification } from "@/lib/types";

export const mockNotifications: Notification[] = [
  {
    id: "notif-001",
    userId: "user-008",
    title: "Enrollment Confirmed",
    message: "Your enrollment in BSc Computer Science (Jan 2024 Intake) has been confirmed.",
    category: "enrollment",
    isRead: true,
    createdAt: "2024-01-16T10:35:00Z",
    linkTo: "/dashboard/enrollment",
  },
  {
    id: "notif-002",
    userId: "user-008",
    title: "Payment Received",
    message: "Payment of UGX 4,500,000 for BSc Computer Science has been received successfully.",
    category: "payment",
    isRead: true,
    createdAt: "2024-01-16T10:31:00Z",
    linkTo: "/dashboard/payments",
  },
  {
    id: "notif-003",
    userId: "user-008",
    title: "Upcoming Live Class",
    message: "Data Structures - Binary Trees starts in 30 minutes. Join via Zoom.",
    category: "class",
    isRead: false,
    createdAt: "2024-11-18T08:30:00Z",
    linkTo: "/dashboard/virtual-learning",
  },
  {
    id: "notif-004",
    userId: "user-008",
    title: "Exam Deadline Approaching",
    message: "Data Structures Mid-Semester Quiz is due in 2 days. Don't forget to submit.",
    category: "exam",
    isRead: false,
    createdAt: "2024-11-18T07:00:00Z",
    linkTo: "/dashboard/examinations",
  },
  {
    id: "notif-005",
    userId: "user-009",
    title: "Enrollment Confirmed",
    message: "Your enrollment in BSc Computer Science (Jan 2024 Intake) has been confirmed.",
    category: "enrollment",
    isRead: true,
    createdAt: "2024-01-17T14:20:00Z",
    linkTo: "/dashboard/enrollment",
  },
  {
    id: "notif-006",
    userId: "user-009",
    title: "Exam Result Available",
    message: "Your result for Data Structures Mid-Semester Quiz is now available. Score: 62/100.",
    category: "exam",
    isRead: false,
    createdAt: "2024-11-21T10:00:00Z",
    linkTo: "/dashboard/examinations",
  },
  {
    id: "notif-007",
    userId: "user-004",
    title: "New Submission",
    message: "Aisha Nakato submitted Software Engineering Assignment 1.",
    category: "exam",
    isRead: false,
    createdAt: "2024-11-25T16:05:00Z",
    linkTo: "/dashboard/examinations",
  },
  {
    id: "notif-008",
    userId: "user-004",
    title: "Class Reminder",
    message: "Your class 'Graph Algorithms - BFS & DFS' is scheduled for Nov 25 at 09:00.",
    category: "class",
    isRead: false,
    createdAt: "2024-11-24T18:00:00Z",
    linkTo: "/dashboard/virtual-learning",
  },
  {
    id: "notif-009",
    userId: "user-011",
    title: "Payment Pending",
    message: "Your payment of UGX 5,200,000 for BSc Civil Engineering is still pending.",
    category: "payment",
    isRead: false,
    createdAt: "2024-03-10T09:00:00Z",
    linkTo: "/dashboard/payments",
  },
  {
    id: "notif-010",
    userId: "user-010",
    title: "New Study Material",
    message: "Marketing Case Studies - East Africa has been uploaded for Principles of Marketing.",
    category: "enrollment",
    isRead: true,
    createdAt: "2024-02-20T12:00:00Z",
    linkTo: "/dashboard/materials",
  },
  {
    id: "notif-011",
    userId: "user-005",
    title: "Course Unit Approved",
    message: "Your course unit 'Introduction to Machine Learning' has been rejected by the admin.",
    category: "enrollment",
    isRead: true,
    createdAt: "2024-10-15T11:00:00Z",
    linkTo: "/dashboard/course-units",
  },
  {
    id: "notif-012",
    userId: "user-012",
    title: "Upcoming Live Class",
    message: "JavaScript DOM Manipulation starts tomorrow at 15:00. Join via Zoom.",
    category: "class",
    isRead: false,
    createdAt: "2024-11-21T18:00:00Z",
    linkTo: "/dashboard/virtual-learning",
  },
];
