import type { User } from "@/lib/types";

export const mockUsers: User[] = [
  {
    id: "user-001",
    name: "Prof. Barnabas Nawangwe",
    email: "b.nawangwe@mak.ac.ug",
    role: "super_admin",
    avatar: undefined,
    createdAt: "2022-01-15T08:00:00Z",
  },
  {
    id: "user-002",
    name: "Dr. Sarah Kiggundu",
    email: "s.kiggundu@mak.ac.ug",
    role: "admin",
    avatar: undefined,
    createdAt: "2022-03-10T09:30:00Z",
  },
  {
    id: "user-003",
    name: "Dr. Joseph Muwanga",
    email: "j.muwanga@mak.ac.ug",
    role: "admin",
    avatar: undefined,
    createdAt: "2022-04-20T10:00:00Z",
  },
  {
    id: "user-004",
    name: "Dr. Agnes Namutebi",
    email: "a.namutebi@mak.ac.ug",
    role: "lecturer",
    avatar: undefined,
    createdAt: "2022-06-01T08:00:00Z",
  },
  {
    id: "user-005",
    name: "Dr. Peter Ssekitoleko",
    email: "p.ssekitoleko@mak.ac.ug",
    role: "lecturer",
    avatar: undefined,
    createdAt: "2022-06-15T09:00:00Z",
  },
  {
    id: "user-006",
    name: "Dr. Florence Nakamya",
    email: "f.nakamya@mak.ac.ug",
    role: "lecturer",
    avatar: undefined,
    createdAt: "2022-07-01T08:30:00Z",
  },
  {
    id: "user-007",
    name: "Dr. Ronald Mukisa",
    email: "r.mukisa@mak.ac.ug",
    role: "lecturer",
    avatar: undefined,
    createdAt: "2022-08-10T10:00:00Z",
  },
  {
    id: "user-008",
    name: "Aisha Nakato",
    email: "a.nakato@students.mak.ac.ug",
    role: "student",
    avatar: undefined,
    createdAt: "2023-01-10T08:00:00Z",
  },
  {
    id: "user-009",
    name: "Brian Ochieng",
    email: "b.ochieng@students.mak.ac.ug",
    role: "student",
    avatar: undefined,
    createdAt: "2023-01-15T09:00:00Z",
  },
  {
    id: "user-010",
    name: "Grace Atim",
    email: "g.atim@students.mak.ac.ug",
    role: "student",
    avatar: undefined,
    createdAt: "2023-02-01T08:30:00Z",
  },
  {
    id: "user-011",
    name: "David Mugisha",
    email: "d.mugisha@students.mak.ac.ug",
    role: "student",
    avatar: undefined,
    createdAt: "2023-02-20T10:00:00Z",
  },
  {
    id: "user-012",
    name: "Esther Nambi",
    email: "e.nambi@students.mak.ac.ug",
    role: "student",
    avatar: undefined,
    createdAt: "2023-03-05T08:00:00Z",
  },
];
